
import streamlit as st
st.set_page_config(page_title="QuLab", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("QuLab")
st.divider()
st.markdown("""
In this lab, we develop and evaluate Probability of Default (PD) models. Probability of Default is a key risk parameter used in financial institutions to quantify the likelihood that a borrower will default on their debt obligations over a specific time horizon. This application provides an interactive interface to explore different stages of PD model development, including data preparation, model training (Logistic Regression and Gradient Boosting), calibration, threshold selection, and performance evaluation.

### Business Logic

Our primary goal is to build a robust model that accurately predicts whether a customer will default on their credit card payment next month. We will follow a structured approach:

1.  **Data Loading and Preprocessing**: We start by loading the credit card default dataset. Missing values will be handled, and categorical features will be appropriately encoded.

2.  **Exploratory Data Analysis (EDA)**: We will visualize the class balance of our target variable (default vs. non-default) and explore correlations between numerical features to understand data patterns.

3.  **Model Training**: We will train two types of models:
    *   **Logistic Regression**: A linear model that estimates the probability of a binary outcome. It provides interpretable coefficients and serves as a strong baseline.
    *   **Gradient Boosting**: A powerful ensemble technique that builds a model in a stage-wise fashion, allowing for complex non-linear relationships and often achieving higher accuracy.

4.  **Model Calibration**: Since models often output probabilities that are not truly reflective of actual probabilities, we will calibrate our models using Platt scaling on a validation set. This ensures that a predicted probability of, say, 0.75 truly means there's a 75% chance of default.

5.  **Threshold Selection**: For converting predicted probabilities into binary default/non-default decisions, we need an optimal threshold ($\tau^*$). We will use Youden's J statistic on the validation set to find this threshold, which maximizes the difference between True Positive Rate (TPR) and False Positive Rate (FPR).
    
    $$J = TPR - FPR$$

6.  **Final Evaluation**: The performance of our calibrated models will be assessed on an unseen test set using various metrics:
    *   **ROC AUC**: Measures the ability of the model to distinguish between classes.
    *   **PR AUC**: Particularly useful for imbalanced datasets, it focuses on the trade-off between precision and recall.
    *   **KS-statistic**: Measures the maximum difference between the cumulative true positive and cumulative false positive rates.
    *   **Brier Score**: Quantifies the accuracy of probabilistic predictions.
    *   **Accuracy, Precision, Recall, F1-score**: Standard classification metrics calculated at the selected optimal threshold.

Through this interactive application, users can compare model performance, visualize key aspects like calibration and ROC curves, and understand the impact of selecting different operating thresholds.
""")
# Your code starts here
page = st.sidebar.selectbox(label="Navigation", options=["Data Preparation & EDA", "Model Training & Calibration", "Model Evaluation"])
if page == "Data Preparation & EDA":
    from application_pages.page1 import run_page1
    run_page1()
elif page == "Model Training & Calibration":
    from application_pages.page2 import run_page2
    run_page2()
elif page == "Model Evaluation":
    from application_pages.page3 import run_page3
    run_page3()
# Your code ends


# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@qusandbox.com](mailto:info@qusandbox.com)
''')
